# Generated by Django 4.0.5 on 2022-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism Familya')),
                ('phone', models.CharField(max_length=200, verbose_name='Telfon raqam')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Rasm', verbose_name='Rasm')),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
