# Generated by Django 4.0.5 on 2022-07-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(null=True, upload_to='Rasm', verbose_name='Rasm'),
        ),
    ]
