# Generated by Django 4.0.5 on 2022-07-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='Rasm', verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
