# Generated by Django 4.0.5 on 2022-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HodAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism Familya')),
                ('phone', models.CharField(max_length=200, verbose_name='Telfon raqam')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('password', models.CharField(max_length=200, verbose_name='Parol')),
            ],
        ),
    ]
